### ISSUE TITLE
feature request: override CSS from config

### ISSUE THREAD

**Issue by hotchemi** [LukasJoswiak/etch#12]
First of all, thank you for the awesome theme! I'm using it for my personal blog website.

Now I'd like to customize a bit of default CSS(width and font-family a bit) and it'd be great if I can inject my CSS via config.toml. Of course I can fork and customise but it's a bit cumbersome and also I'd like to follow the latest update as well.

Thank you in advance!

ref: https://discourse.gohugo.io/t/how-to-override-css-classes-with-hugo/3033/4

**Comment by burtonr** [comment]
I agree, this would be a great feature. :+1:

**Comment by LukasJoswiak** [comment]
Hi, thanks for opening an issue. I've been thinking about this for a while, but I'm not sure I'm convinced of how necessary it is. This seems like (as you mentioned) what forking is meant to do. Forks can be [kept up to date with the upstream repository](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) as well. A more lightweight alternative to forking is to just modify the CSS in the theme after adding it as a submodule.

I did look into implementing this. Currently, the CSS files in [`assets/css/`](https://github.com/LukasJoswiak/etch/tree/master/assets/css) are [combined into a single file and minified](https://github.com/LukasJoswiak/etch/blob/master/layouts/partials/head.html#L28). The goal is to keep the number of network requests down (it [can be argued whether this is a worthwhile goal](https://stackoverflow.com/a/49397312/986991)). Anyway, it appears that `resources.Get` can only read files from the `assets` folder within the theme folder and not from within the user's website folder. This means it would be necessary to make extra network requests for each user defined stylesheet. Since I'm not yet convinced how necessary this feature is in the first place I'm hesitant to go ahead with implementing it. I'm happy to keep discussion open though.

**Comment by LukasJoswiak** [comment]
It's been a while and I still think forking is the way to go for changes, so I'm going to close this issue.
